package com.osacky.flank.gradle

import org.gradle.api.file.RegularFileProperty

data class FladleConfigImpl(
  internal val name: String,
  override var projectId: String?,
  override val serviceAccountCredentials: RegularFileProperty,
  override var useOrchestrator: Boolean,
  override var autoGoogleLogin: Boolean,
  override var devices: List<Map<String, String>>,
  override var testTargets: List<String>,
  override var shardTime: Int?,
  override var testShards: Int?,
  override var repeatTests: Int?,
  override var smartFlankGcsPath: String?,
  override var resultsHistoryName: String?,
  override var flakyTestAttempts: Int,
  override var directoriesToPull: List<String>,
  override var filesToDownload: List<String>,
  override var environmentVariables: Map<String, String>,
  override var timeoutMin: Int,
  override var recordVideo: Boolean,
  override var performanceMetrics: Boolean,
  override var resultsBucket: String?,
  override var keepFilePath: Boolean,
  override var resultsDir: String?,
  override var additionalTestApks: Map<String, List<String>>,
  override var runTimeout: String? = null,
  override var ignoreFailedTests: Boolean = false,
  override var disableSharding: Boolean = false,
  override var smartFlankDisableUpload: Boolean = false,
  override var testRunnerClass: String? = null,
  override var localResultsDir: String? = null,
  override var numUniformShards: Int? = null,
  override var clientDetails: Map<String, String> = emptyMap(),
  override var testTargetsAlwaysRun: List<String> = emptyList(),
  override var otherFiles: Map<String, String> = emptyMap(),
  override var networkProfile: String? = null
) : FladleConfig
