name: "CI"
on: [push, pull_request]
jobs:
  validation:
    name: "Building"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: gradle/actions/wrapper-validation@v5
    - name: "Set up JDK 17"
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: gradle/actions/setup-gradle@v5
      name: Setup Gradle
    - name: Check Fladle
      run: ./gradlew assembleDebug assembleDebugAndroidTest printYml check :fladle-plugin:check
    - name: Publish Snapshot
      if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      run: ./gradlew :fladle-plugin:publishToMavenCentral --no-configuration-cache
